# Generated by Django 4.2.7 on 2023-12-02 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 2, 14, 17, 19, 156581, tzinfo=datetime.timezone.utc)),
        ),
    ]
