# Generated by Django 4.2.7 on 2023-12-09 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_notesgroup_user_alter_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 21, 55, 57, 26654, tzinfo=datetime.timezone.utc)),
        ),
    ]
